import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik, Inter } from "next/font/google";
import "./globals.css";

import MenuIcon from "./components/icons/MenuIcon";
import { MattehjelpLogo } from "./components/mattehjelplogo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  weight: ['400', '500', '600', '700'],
  subsets: ['latin']
});

const inter = Inter({
  variable: "--font-inter",
  weight: ['300', '400', '500'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rubik.variable} ${inter.variable} antialiased`}
      >
        <header className="bg-header border-b border-border text-white p-4 text-center bg-heading flex justify-between">
          <MattehjelpLogo />
          <MenuIcon className="left-0 text-white w-12 h-12"/>
        </header>
        {children}
        <footer className="bg-slage-900 text-white p-4 text-center">
          Hello wrodl
        </footer>
      </body>
    </html>
  );
}
