import type { Metadata } from "next";
import { Geist, Geist_Mono, Rubik } from "next/font/google";
import "./globals.css";

import MenuIcon from "./components/icons/MenuIcon";
import MatteHjelp from "./components/icons/MatteHjelp"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--font-rubik",
  weight: ['400', '500', '700'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${rubik.variable} antialiased`}
      >
        <header className="bg-slate-900 text-white p-4 text-center flex justify-between">
          <div className="flex bg-red-400 pb-2">
            <MatteHjelp className="text-white w-12 h-12 bg-red-800"/>
            <p className="font-[family-name:var(--font-rubik)] bg-red-200">Matte Hjelp</p>
          </div>
          <MenuIcon className="left-0 text-white w-12 h-12"/>
        </header>
        {children}
        <footer className="bg-slage-900 text-white p-4 text-center">
          Hello wrodl
        </footer>
      </body>
    </html>
  );
}
